### ISSUE TITLE
unable to find properties files

### ISSUE THREAD

**Issue by appkery** [allusernamestakenexceptthis/thymeleaf-i18n-helper#1]
It doesn't find properties files under thymeleaf/resources directory.

**Comment by allusernamestakenexceptthis** [comment]
Thanks for reporting this. I'll check and will update thread.

Meanwhile, have you tried setting the properties location in settings?

**Comment by appkery** [comment]
It doesn't find files with the name like base_en.properties, base_ko.properties, etc.
But, it finds base.properites well.
Thanks.
